# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='objective',
        ),
    ]
