# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0003_club_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='objective',
            field=models.CharField(default='objective', max_length=1000, null=True),
        ),
    ]
