# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookexchange.Student'),
        ),
        migrations.AddField(
            model_name='pending_transactions',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookexchange.Student'),
        ),
        migrations.AddField(
            model_name='pending_transactions',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookexchange.Seller'),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together=set([('book_name', 'seller_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='pending_transactions',
            unique_together=set([('buyer_id', 'seller')]),
        ),
    ]
