# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20160305_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(),
        ),
    ]
