# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20160305_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_reg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
