# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0012_auto_20160310_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_part',
            field=models.IntegerField(),
        ),
    ]
