# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0016_auto_20160311_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='event',
            name='usn',
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
