# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(max_length=120)),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(default='')),
                ('venue', models.CharField(max_length=120, null=True)),
                ('no_part', models.IntegerField()),
                ('no_reg', models.IntegerField(blank=True, null=True)),
                ('contact_info', models.TextField(default='')),
                ('event_desc', models.TextField(null=True)),
                ('own_form', models.URLField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='./tester/static')),
                ('requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(default='', max_length=120)),
                ('event_id', models.IntegerField()),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(default='abc@xyz.com', max_length=254, null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=3, null=True)),
                ('sem', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('D_O_B', models.DateField()),
                ('branch', models.CharField(choices=[('CSE', 'Computer Engineering'), ('ISE', 'Information Engineering'), ('ME', 'Mechanical Engineering'), ('ECE', 'Electronics Engineering'), ('EEE', 'Electrical Engineering'), ('TE', 'Telecom Engineering'), ('BT', 'Bio-Technology'), ('CV', 'Civil Engineering')], max_length=3)),
                ('sem', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], max_length=1)),
                ('club_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([('event_id', 'usn', 'club_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('club_id', 'event_id')]),
        ),
    ]
