# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='./tester/static'),
        ),
        migrations.AlterUniqueTogether(
            name='pending_transactions',
            unique_together=set([('buyer_id', 'seller', 'book_name')]),
        ),
    ]
