# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('event_id', models.IntegerField()),
                ('comment', models.CharField(max_length=100000000000000)),
                ('creat_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='member',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='usn',
        ),
        migrations.AlterUniqueTogether(
            name='pending_transactions',
            unique_together=set([('buyer_id', 'seller', 'book_name')]),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set([('usn', 'creat_date')]),
        ),
    ]
