# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_pending_transactions_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_transactions',
            name='book_name',
        ),
    ]
