# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
