# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20160416_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.Signup'),
        ),
    ]
