# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20160403_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club_id',
            field=models.CharField(max_length=120),
        ),
    ]
