# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_auto_20160416_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='buyer_id',
            field=models.ForeignKey(db_column='usn', on_delete=django.db.models.deletion.CASCADE, to='tester.Signup'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.ForeignKey(db_column='usn', on_delete=django.db.models.deletion.CASCADE, to='tester.Signup'),
        ),
    ]
