# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_auto_20160403_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='D_O_B',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='signup',
            name='dept',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
