# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_auto_20160404_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='register',
            name='dept',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
