# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_auto_20160418_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='club_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
