# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('club_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
    ]
