# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_event_own_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([('event_id', 'usn')]),
        ),
    ]
