# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_auto_20160309_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_info',
            field=models.TextField(default=9876543210L),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='sem',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='usn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
