# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_auto_20160309_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='usn',
            field=models.CharField(max_length=10),
        ),
    ]
