# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0010_auto_20160309_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254, null=True),
        ),
    ]
