# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0011_auto_20160309_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='own_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
