# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_auto_20160310_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='club_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([('event_id', 'usn', 'club_id')]),
        ),
    ]
