# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_auto_20160311_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('D_O_B', models.DateField()),
                ('branch', models.CharField(choices=[('CSE', 'Computer Engineering'), ('ISE', 'Information Engineering'), ('ME', 'Mechanical Engineering'), ('ECE', 'Electronics Engineering'), ('EEE', 'Electrical Engineering'), ('TE', 'Telecom Engineering'), ('BT', 'Bio-Technology'), ('CV', 'Civil Engineering')], max_length=3)),
                ('sem', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], max_length=1)),
                ('club_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='requirements',
        ),
    ]
