# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0017_auto_20160311_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
