# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0019_auto_20160314_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='./tester/static'),
        ),
    ]
