# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0021_auto_20160317_0346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('club_id', 'event_id')]),
        ),
    ]
