# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('objective', models.CharField(default='objective', max_length=1000, null=True)),
                ('members', models.CharField(max_length=1000, null=True)),
                ('fb_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(default='')),
                ('venue', models.CharField(max_length=120, null=True)),
                ('no_part', models.IntegerField()),
                ('no_reg', models.IntegerField(blank=True, null=True)),
                ('contact_info', models.TextField(default='')),
                ('event_desc', models.TextField(null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('own_form', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('club_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='welcomepage.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('email', models.EmailField(default='abc@xyz.com', max_length=254, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('sem', models.IntegerField(null=True)),
                ('club_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='welcomepage.Club')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('club_id', 'event_id')]),
        ),
    ]
